author: Edward Linscott
title: Edward Linscott
name: Edward Linscott
email: ebl27[at]cam.ac.uk
description: PhD student at the University of Cambridge
show_downloads: false
markdown: kramdown
theme: minima 
twitter_username: ed_linscott
github_username: elinscott
bitbucket_username: elinscott
linkedin_username: elinscott
departmental_website: http://www.tcm.phy.cam.ac.uk/profiles/ebl27/
scholar_id: 4_ejng0AAAAJ&hl
orcid_id: 0000-0002-4967-9873
google_analytics: UA-122965805-1
exclude:
    - Gemfile
    - Gemfile.lock
