# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Edward Linscott
title: Edward Linscott
name: Edward Linscott
email: edward.linscott[at]psi.ch
description: Postdoc at PSI
show_downloads: false
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Edward Linscott, postdoctoral researcher at PSI
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elinscott.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
twitter_username: ed_linscott
github_username: elinscott
bitbucket_username: elinscott
orcid_id: 0000-0002-4967-9873
linkedin_username: elinscott
departmental_website: https://www.psi.ch/en/lms/people/edward-baxter-linscott
scholar_id: 4_ejng0AAAAJ&hl
plugins:
  - jekyll-gist

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: [".well-known"]
